# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    # Test-specific ignores
    "S101", # Use of assert detected (tests need assert)
    "S106", # Possible hardcoded password in tests (test data is fine)
    "S105", # Possible hardcoded password in tests (test data is fine)
    "SLF001", # Private member access in tests (needed for testing)
    "PLR2004", # Magic numbers in tests are fine
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25